compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.production]
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.preview]
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
